# Generated by Django 3.1.1 on 2020-10-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0002_auto_20201013_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(default='escription'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
