# Generated by Django 3.1.1 on 2020-10-25 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0004_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
    ]
