# Generated by Django 3.1.2 on 2020-10-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions_answers', '0006_auto_20201025_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
